image: node:12-alpine

stages:
  - setup
  - format
  - lint
  - deploy # dummy stage to follow the template guidelines

cache:
  paths:
    - ./node_modules/

setup:
  stage: setup
  script:
    - npm install
  artifacts:
    paths:
      - ./node_modules/

format:
  stage: format
  script:
    - npm run format

lint:
  stage: lint
  script:
    - npm run eslint

audit:
  stage: lint
  script:
    - npm audit --production

test:
  stage: test
  script:
    - npm run test
  dependencies:
    - install_dependencies
  artifacts:
    paths:
      - coverage/
    reports:
      junit: coverage/junit.xml
    when: always
    expire_in: 1 week
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
